server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Bloquear acesso de bots à rota do admin
    location /gestor-nlf-admin {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
        
        # Opcional: IP Allowlist pode ser configurado aqui ou no Traefik
        # allow 10.0.0.0/8;
        # deny all;
    }
}
