version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
    container_name: nlf-catalogo-frontend
    ports:
      - "3000:80"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: nlf-catalogo-api
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    restart: unless-stopped

networks:
  default:
    name: nlf_network
